# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - service4/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2c96971d-dd89-4c0e-ad8b-1b41cca3b10f'
  imageRepository: 'ecomsiteservice4'
  containerRegistry: 'ecomsite.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/service4/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
 name: 'azurecicdagent'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build 
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'service4/Dockerfile'
        tags: '$(tag)'
  stage: push
  displayName: push 
  jobs:
  - job: push
    displayName: push
    steps:
    - task: Docker@2
      displayName: push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
